services:
  app1: 
    build: .
    container_name: app1
    ports:
      - "8080:8080"
    networks:
    - chat-app-network
  app2:
    build: .
    container_name: app2
    ports:
      - "8081:8080"
    networks:
    - chat-app-network
  app3:
    build: .
    container_name: app3
    ports:
      - "8082:8080"
    networks:
    - chat-app-network

  nginx:
    image: nginx:latest
    ports: 
      - "4000:4000"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - chat-app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  chat-app-network:
    driver: overlay
